const CLOUD_NAME = import.meta.env.VITE_CLOUDINARY_CLOUD_NAME;
const CLOUD_PRESET = import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET;
const BASE_URL = import.meta.env.VITE_BACKEND_URL 
export { CLOUD_NAME, CLOUD_PRESET, BASE_URL };
